before:
  hooks:
    - go mod tidy
builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -tags=netgo
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cli/slsa-verifier
    binary: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
archives:
  - format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  draft: false
changelog:
  skip: true
