name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.1.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@9c96258789e5d9e85fe4ca86115ba4cc62b780cf # tag=v2.4.1
