name: Schedule cli
on:
  workflow_run:
    workflows: ["Pre submits cli"]
    types: [completed]
    branches: [main]

permissions: read-all

env:
  GH_TOKEN: ${{ github.token }}
  ISSUE_REPOSITORY: ${{ github.repository }}

jobs:
  if-failed:
    runs-on: ubuntu-latest
    # See https://github.com/orgs/community/discussions/26238.
    steps:
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: event_name
      - name: Check event name
        id: name
        run: |
          name=$(cat ./event_name.txt)
          ctned="false"
          if [[ "$name" == "schedule" ]] || [[ "$name" == "workflow_dispatch" ]]; then
            ctned="true"
          fi
          echo "continue=$ctned" >> $GITHUB_OUTPUT
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        if: steps.name.outputs.continue == 'true'
        with:
          ref: main
          repository: slsa-framework/example-package
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion != 'success'
      - run: ./.github/workflows/scripts/e2e-report-success.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion == 'success'
