name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.1.2

      - name: setup-go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # tag=v3.2.1
        with:
          go-version: '1.18'

      - name: Run tests for verifier
        run: |
          set -euo pipefail

          go mod vendor

          # Build cli
          go build -mod=vendor -o slsa-verifier ./cli/slsa-verifier/main.go

          # Builder service
          go build -mod=vendor -o service ./cli/experimental/service/main.go

          # Tests
          go test -mod=vendor -v ./...
