name: Pre submits cli
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  # Used in combination with schedule.cli.yml
  # to avoid duplicating the test code.
  schedule:
    - cron: "25 6 * * 5"

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup-go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: "go.mod"
          # not needed but gets rid of warnings
          cache: false

      - name: Save event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "$EVENT_NAME" > ./event_name.txt

      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: event_name
          path: ./event_name.txt

      - name: Run tests for verifier
        run: |
          set -euo pipefail
          make regression-test
