name: Pre submits Lint

on: [pull_request]

permissions:
  # Needed to check out the repo.
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - working-directory: actions/installer
        run: make lint
