name: Pre submits cli
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  # Used in combination with schedule.cli.yml
  # to avoid duplicating the test code.
  schedule:
    - cron: "25 6 * * 5"

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup-go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: "go.mod"
          # not needed but gets rid of warnings
          cache: false

      - name: Save event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "$EVENT_NAME" > ./event_name.txt

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: event_name
          path: ./event_name.txt

      - name: Run tests for verifier
        run: |
          set -euo pipefail
          make regression-test
