name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3

      - name: setup-go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a # v3
        with:
          go-version: '1.18'

      - name: Run tests for verifier
        run: |
          set -euo pipefail

          go mod vendor
          # Build
          go build -mod=vendor
          # Tests
          go test -mod=vendor -v ./...
