name: Pre submits cli
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  # Used in combination with schedule.cli.yml
  # to avoid duplicating the test code.
  schedule:
    - cron: "25 6 * * 5"

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: setup-go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "go.mod"
          # not needed but gets rid of warnings
          cache: false

      - name: Save event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          echo "$EVENT_NAME" > ./event_name.txt

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: event_name
          path: ./event_name.txt

      - name: Run tests for verifier
        run: |
          set -euo pipefail
          make regression-test
