name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v2.3.4
        
      - name: setup-go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: '1.17'
       
      - name: Run tests for verifier
        run: |
          set -euo pipefail
          
          go mod vendor
          # Build
          go build -mod=vendor
          # Tests
          go test -mod=vendor -v ./...
