name: Pre submits
on: [pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.1.2

      - name: setup-go
        uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3.3.0
        with:
          go-version: '1.18'

      - name: Run tests for verifier
        run: |
          set -euo pipefail

          go mod vendor

          # Build cli
          go build -mod=vendor -o slsa-verifier ./cli/slsa-verifier/

          # Builder service
          go build -mod=vendor -o service ./cli/experimental/service/

          # Tests
          go test -mod=vendor -v ./...
