name: Verifier releaser

on: 
  # For manual tests.
  workflow_dispatch:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4`.

permissions: read-all

jobs:
  builder:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v0.0.1
    with:
      go-version: 1.18
      config-file: .github/config-release.yml
      compile-builder: true
