name: Verifier releaser

on: 
  # For manual tests.
  workflow_dispatch:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4`.
  # Run daily as a dry-run/test.
  schedule:
    - cron: '0 1 * * *'

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ISSUE_REPOSITORY: slsa-framework/slsa-verifier

jobs:
  builder:
    permissions:
      actions: read # For the detection of GitHub Actions environment.
      id-token: write # For signing.
      contents: write # For asset uploads.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.2.0
    with:
      go-version: 1.18
      config-file: .github/config-release.yml
      compile-builder: true

  # In case this fails, e.g. build configuration changes, file an issue in slsa-verifier
  if-failed:
    runs-on: ubuntu-latest
    needs: [builder]
    if: always() && needs.builder.result == 'failure'
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2
        with:
          repository: slsa-framework/example-package
      - run: |
          set -euo pipefail

          ./.github/workflows/scripts/e2e-report-failure.sh
