on: [push]

jobs:
  default_installer:
    runs-on: ubuntu-latest
    name: Default installation
    steps:
      - name: Default install
        uses: slsa-framework/slsa-verifier/actions/install@main
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v001:
    runs-on: ubuntu-latest
    name: Install v0.0.1
    steps:
      - name: Install verifier v0.0.1
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v0.0.1
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v100:
    runs-on: ubuntu-latest
    name: Install v1.0.0
    steps:
      - name: Install verifier v1.0.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.0.0
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v101:
    runs-on: ubuntu-latest
    name: Install v1.0.1
    steps:
      - name: Install verifier v1.0.1
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.0.1
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v102:
    runs-on: ubuntu-latest
    name: Install v1.0.2
    steps:
      - name: Install verifier v1.0.2
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.0.2
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v110:
    runs-on: ubuntu-latest
    name: Install v1.1.0
    steps:
      - name: Install verifier v1.1.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.1.0
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v111:
    runs-on: ubuntu-latest
    name: Install v1.1.1
    steps:
      - name: Install verifier v1.1.1
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.1.1
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v120:
    runs-on: ubuntu-latest
    name: Install v1.2.0
    steps:
      - name: Install verifier v1.2.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.2.0
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_v130:
    runs-on: ubuntu-latest
    name: Install v1.3.0
    steps:
      - name: Install verifier v1.3.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: v1.3.0
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_main:
    runs-on: ubuntu-latest
    name: Install from main
    steps:
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - name: Install verifier at main
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          verifier-release: main
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_custom_path:
    runs-on: ubuntu-latest
    name: Install in custom directory
    steps:
      - name: Install verifier v1.3.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          install-dir: /tmp/.slsa-verifier
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  installer_job_sudo_enabled:
    runs-on: ubuntu-latest
    name: Install with sudo
    steps:
      - name: Install verifier v1.3.0
        uses: slsa-framework/slsa-verifier/actions/install@main
        with:
          use-sudo: true
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
