permissions: read-all
on:
  push
  schedule:
    - cron: '14 3 * * *'

jobs:
  installer_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        verifier-release: [main, v0.0.1, v1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.1.1, v1.2.0, v1.3.0]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install verifier ${{ matrix.verifier-release }}
        uses: ./actions/install
        with:
          verifier-release: ${{ matrix.verifier-release }}
      - name: Run verifier help
        run: slsa-verifier --help
        shell: bash
  invalid_version_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - shell: bash
        run: |
          if ! $GITHUB_WORKSPACE/actions/install/installer.sh catdog ; then
            exit 0
          fi
          exit 1
  invalid_hash_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - shell: bash
        run: |
          if ! $GITHUB_WORKSPACE/actions/install/installer.sh test-force-checksum-error ; then
            exit 0
          fi
          exit 1
  invalid_provenance_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - shell: bash
        run: |
          if ! $GITHUB_WORKSPACE/actions/install/installer.sh test-force-provenance-error ; then
            exit 0
          fi
          exit 1
